hotspot: Fix build issue with missing _GNU_SOURCE
  CC       src/hotspot.o
src/hotspot.c: In function ‘hotspot_init’:
src/hotspot.c:516:39: error: ‘DT_UNKNOWN’ undeclared (first use in this function)
  516 |                 if (dirent->d_type == DT_UNKNOWN) {
      |                                       ^~~~~~~~~~
src/hotspot.c:516:39: note: each undeclared identifier is reported only once for each function it appears in
src/hotspot.c:519:46: error: ‘DT_REG’ undeclared (first use in this function)
  519 |                 } else if (dirent->d_type != DT_REG &&
      |                                              ^~~~~~
src/hotspot.c:520:67: error: ‘DT_LNK’ undeclared (first use in this function)
  520 |                                                 dirent->d_type != DT_LNK) {
      |                                                                   ^~~~~~