epa-peap: Fix build issue with missing _GNU_SOURCE
  CC       src/eap-peap.o
src/eap-peap.c: In function ‘eap_peap_phase2_complete’:
src/eap-peap.c:120:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  120 |         explicit_bzero(peap_state->key, sizeof(peap_state->key));
      |         ^~~~~~~~~~~~~~