eap-sim: Fix build issue with missing _GNU_SOURCE
  CC       src/eap-sim.o
src/eap-sim.c: In function ‘eap_sim_clear_secrets’:
src/eap-sim.c:132:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  132 |         explicit_bzero(sim->mk, sizeof(sim->mk));
      |         ^~~~~~~~~~~~~~