resolve: Fix build issue with missing _GNU_SOURCE
  CC       src/resolve.o
src/resolve.c: In function ‘resolvconf_invoke’:
src/resolve.c:386:30: error: implicit declaration of function ‘popen’; did you mean ‘fopen’? [-Wimplicit-function-declaration]
  386 |                 resolvconf = popen(cmd, "w");
      |                              ^~~~~
      |                              fopen
src/resolve.c:386:28: error: assignment to ‘FILE *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  386 |                 resolvconf = popen(cmd, "w");
      |                            ^
src/resolve.c:390:28: error: assignment to ‘FILE *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  390 |                 resolvconf = popen(cmd, "r");
      |                            ^
src/resolve.c:403:17: error: implicit declaration of function ‘pclose’; did you mean ‘close’? [-Wimplicit-function-declaration]
  403 |         error = pclose(resolvconf);
      |                 ^~~~~~
      |                 close