network: Fix build issue with missing _GNU_SOURCE
  CC       src/network.o
src/network.c: In function ‘network_reset_psk’:
src/network.c:114:17: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  114 |                 explicit_bzero(network->psk, 32);
      |                 ^~~~~~~~~~~~~~