crypto: Fix build issue with missing _GNU_SOURCE
  CC       src/crypto.o
src/crypto.c: In function ‘aes_unwrap’:
src/crypto.c:187:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  187 |         explicit_bzero(&b[1], 8);
      |         ^~~~~~~~~~~~~~