eap-ttls: Fix build issue with missing _GNU_SOURCE
  CC       src/eap-ttls.o
src/eap-ttls.c: In function ‘avp_builder_free’:
src/eap-ttls.c:159:17: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  159 |                 explicit_bzero(builder->buf, builder->pos);
      |                 ^~~~~~~~~~~~~~