eap-pwd: Fix build issue with missing _GNU_SOURCE
  CC       src/eap-pwd.o
src/eap-pwd.c: In function ‘eap_pwd_free’:
src/eap-pwd.c:177:17: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  177 |                 explicit_bzero(pwd->password, strlen(pwd->password));
      |                 ^~~~~~~~~~~~~~