handshake: Fix build issue with missing _GNU_SOURCE
  CC       src/handshake.o
src/handshake.c: In function ‘handshake_state_unref’:
src/handshake.c:151:17: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  151 |                 explicit_bzero(s->passphrase, strlen(s->passphrase));
      |                 ^~~~~~~~~~~~~~