wired: Fix build issue with missing _GNU_SOURCE
  CC       wired/ethdev.o
wired/ethdev.c: In function ‘pae_open’:
wired/ethdev.c:331:40: error: ‘SO_ATTACH_FILTER’ undeclared (first use in this function)
  331 |         if (setsockopt(fd, SOL_SOCKET, SO_ATTACH_FILTER,
      |                                        ^~~~~~~~~~~~~~~~
wired/ethdev.c:331:40: note: each undeclared identifier is reported only once for each function it appears in