udev: Fix build issue with missing _GNU_SOURCE
  CC       src/udev.o
src/udev.c: In function ‘attach_filter’:
src/udev.c:129:40: error: ‘SO_ATTACH_FILTER’ undeclared (first use in this function)
  129 |         if (setsockopt(fd, SOL_SOCKET, SO_ATTACH_FILTER,
      |                                        ^~~~~~~~~~~~~~~~
src/udev.c:129:40: note: each undeclared identifier is reported only once for each function it appears in