dpp: Fix build issue with missing _GNU_SOURCE
  CC       src/dpp.o
src/dpp.c: In function ‘dpp_reset’:
src/dpp.c:536:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  536 |         explicit_bzero(dpp->r_nonce, dpp->nonce_len);
      |         ^~~~~~~~~~~~~~