ft: Fix build issue with missing alloca.h include
  CC       src/ft.o
src/ft.c: In function ‘ft_prepare_handshake’:
src/ft.c:846:16: error: implicit declaration of function ‘alloca’; did you mean ‘calloc’? [-Wimplicit-function-declaration]
  846 |         rsne = alloca(256);
      |                ^~~~~~
      |                calloc
src/ft.c:846:14: error: assignment to ‘uint8_t *’ {aka ‘unsigned char *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  846 |         rsne = alloca(256);
      |              ^
src/ft.c:887:13: error: assignment to ‘uint8_t *’ {aka ‘unsigned char *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  887 |         fte = alloca(256);
      |             ^