client: Fix build issue with missing _GNU_SOURCE
  CC       client/dpp.o
client/dpp.c: In function ‘get_uri_method_callback’:
client/dpp.c:174:13: error: implicit declaration of function ‘popen’; did you mean ‘fopen’? [-Wimplicit-function-declaration]
  174 |         f = popen(cmd, "r");
      |             ^~~~~
      |             fopen
client/dpp.c:174:11: error: assignment to ‘FILE *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  174 |         f = popen(cmd, "r");
      |           ^
client/dpp.c:181:9: error: implicit declaration of function ‘pclose’; did you mean ‘close’? [-Wimplicit-function-declaration]
  181 |         pclose(f);
      |         ^~~~~~
      |         close