simutil: Fix build issue with missing _GNU_SOURCE
  CC       src/simutil.o
src/simutil.c: In function ‘eap_aka_derive_primes’:
src/simutil.c:168:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  168 |         explicit_bzero(key, sizeof(key));
      |         ^~~~~~~~~~~~~~