tools: Fix build issue with missing _GNU_SOURCE
  CC       tools/probe-req.o
tools/probe-req.c: In function ‘get_interface_callback’:
tools/probe-req.c:122:22: error: storage size of ‘ifr’ isn’t known
  122 |         struct ifreq ifr;
      |                      ^~~
tools/probe-req.c:155:42: error: ‘IFF_UP’ undeclared (first use in this function)
  155 |         if (r == -1 || !(ifr.ifr_flags & IFF_UP))
      |                                          ^~~~~~
tools/probe-req.c:155:42: note: each undeclared identifier is reported only once for each function it appears in
tools/probe-req.c:122:22: error: unused variable ‘ifr’ [-Werror=unused-variable]
  122 |         struct ifreq ifr;
      |                      ^~~