eapol: Fix build issue with missing _GNU_SOURCE
  CC       src/eapol.o
src/eapol.c: In function ‘eapol_decrypt_key_data’:
src/eapol.c:314:17: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  314 |                 explicit_bzero(key, sizeof(key));
      |                 ^~~~~~~~~~~~~~