erp: Fix build issue with missing _GNU_SOURCE
  CC       src/erp.o
src/erp.c: In function ‘erp_free’:
src/erp.c:357:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  357 |         explicit_bzero(erp->rmsk, sizeof(erp->rmsk));
      |         ^~~~~~~~~~~~~~