wsc: Fix build issue with missing _GNU_SOURCE
  CC       src/wsc.o
src/wsc.c: In function ‘wsc_enrollee_credential_obtained’:
src/wsc.c:211:25: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  211 |                         explicit_bzero(decoded, 32);
      |                         ^~~~~~~~~~~~~~