eap-wsc: Fix build issue with missing _GNU_SOURCE
  CC       src/eap-wsc.o
src/eap-wsc.c: In function ‘encrypted_settings_decrypt’:
src/eap-wsc.c:258:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  258 |         explicit_bzero(decrypted, encrypted_len);
      |         ^~~~~~~~~~~~~~