wscutil: Fix build issue with missing strings.h include
  CC       src/wscutil.o
src/wscutil.c: In function ‘wsc_device_type_from_subcategory_str’:
src/wscutil.c:3043:30: error: implicit declaration of function ‘strcasecmp’; did you mean ‘strncmp’? [-Wimplicit-function-declaration]
 3043 |                         if (!strcasecmp(subcategory_str,
      |                              ^~~~~~~~~~
      |                              strncmp