unit: Fix build issue with missing alloca.h include
  CC       unit/test-sae.o
unit/test-sae.c: In function ‘test_clogging’:
unit/test-sae.c:253:44: error: implicit declaration of function ‘alloca’; did you mean ‘calloc’? [-Wimplicit-function-declaration]
  253 |         struct authenticate_frame *frame = alloca(
      |                                            ^~~~~~
      |                                            calloc
unit/test-sae.c:253:44: error: initialization of ‘struct authenticate_frame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
unit/test-sae.c: In function ‘test_early_confirm’:
unit/test-sae.c:282:44: error: initialization of ‘struct authenticate_frame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  282 |         struct authenticate_frame *frame = alloca(
      |                                            ^~~~~~
unit/test-sae.c: In function ‘test_malformed_commit’:
unit/test-sae.c:323:44: error: initialization of ‘struct authenticate_frame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  323 |         struct authenticate_frame *frame = alloca(
      |                                            ^~~~~~
unit/test-sae.c: In function ‘test_malformed_confirm’:
unit/test-sae.c:341:44: error: initialization of ‘struct authenticate_frame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  341 |         struct authenticate_frame *frame = alloca(
      |                                            ^~~~~~
unit/test-sae.c:352:15: error: assignment to ‘struct authenticate_frame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  352 |         frame = alloca(sizeof(struct authenticate_frame) + sizeof(aa_confirm));
      |               ^
unit/test-sae.c: In function ‘test_bad_group’:
unit/test-sae.c:378:44: error: initialization of ‘struct authenticate_frame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  378 |         struct authenticate_frame *frame = alloca(
      |                                            ^~~~~~
unit/test-sae.c: In function ‘test_bad_confirm’:
unit/test-sae.c:409:44: error: initialization of ‘struct authenticate_frame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  409 |         struct authenticate_frame *frame = alloca(
      |                                            ^~~~~~
unit/test-sae.c: In function ‘test_confirm_after_accept’:
unit/test-sae.c:482:44: error: initialization of ‘struct authenticate_frame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  482 |         struct authenticate_frame *frame = alloca(
      |                                            ^~~~~~
unit/test-sae.c:484:41: error: initialization of ‘struct associate_frame *’ from ‘int’ makes pointer from integer without a cast -Wint-conversion]
  484 |         struct associate_frame *assoc = alloca(sizeof(struct associate_frame));
      |                                         ^~~~~~
unit/test-sae.c: In function ‘test_end_to_end’:
unit/test-sae.c:566:44: error: initialization of ‘struct authenticate_frame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  566 |         struct authenticate_frame *frame = alloca(
      |                                            ^~~~~~
unit/test-sae.c:568:41: error: initialization of ‘struct associate_frame *’ from ‘int’ makes pointer from integer without a cast -Wint-conversion]
  568 |         struct associate_frame *assoc = alloca(sizeof(struct associate_frame));
      |                                         ^~~~~~