eap-gtc: Fix build issue with missing _GNU_SOURCE
  CC       src/eap-gtc.o
src/eap-gtc.c: In function ‘eap_gtc_free’:
src/eap-gtc.c:48:17: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
   48 |                 explicit_bzero(gtc->password, strlen(gtc->password));
      |                 ^~~~~~~~~~~~~~