ap: Fix build issue with missing _GNU_SOURCE
  CC       src/ap.o
src/ap.c: In function ‘ap_reset’:
src/ap.c:286:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  286 |         explicit_bzero(ap->passphrase, sizeof(ap->passphrase));
      |         ^~~~~~~~~~~~~~