eap-aka: Fix build issue with missing _GNU_SOURCE
  CC       src/eap-aka.o
src/eap-aka.c: In function ‘eap_aka_clear_secrets’:
src/eap-aka.c:114:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  114 |         explicit_bzero(aka->mk, sizeof(aka->mk));
      |         ^~~~~~~~~~~~~~