rfkill: Fix build issue with missing _GNU_SOURCE
  CC       src/rfkill.o
In file included from ./ell/ell.h:1,
                 from src/rfkill.c:35:
src/rfkill.c: In function ‘rfkill_init’:
src/rfkill.c:282:49: error: ‘O_CLOEXEC’ undeclared (first use in this function); did you mean ‘FD_CLOEXEC’?
  282 |         fd = L_TFR(open("/dev/rfkill", O_RDWR | O_CLOEXEC));
      |                                                 ^~~~~~~~~
./ell/util.h:348:34: note: in definition of macro ‘L_TFR’
  348 |        do __result = (long int) (expression);      \
      |                                  ^~~~~~~~~~
src/rfkill.c:282:49: note: each undeclared identifier is reported only once for each function it appears in
  282 |         fd = L_TFR(open("/dev/rfkill", O_RDWR | O_CLOEXEC));
      |                                                 ^~~~~~~~~
./ell/util.h:348:34: note: in definition of macro ‘L_TFR’
  348 |        do __result = (long int) (expression);      \
      |                                  ^~~~~~~~~~