fils: Fix build issue with missing _GNU_SOURCE
  CC       src/fils.o
src/fils.c: In function ‘fils_erp_tx_func’:
src/fils.c:117:16: error: implicit declaration of function ‘alloca’; did you mean ‘calloc’? [-Wimplicit-function-declaration]
  117 |         rsne = alloca(256);
      |                ^~~~~~
      |                calloc
src/fils.c:117:14: error: assignment to ‘uint8_t *’ {aka ‘unsigned char *’} from ‘int’ makes pointer from integer without a cast -Wint-conversion]
  117 |         rsne = alloca(256);
      |              ^
src/fils.c: In function ‘fils_derive_key_data’:
src/fils.c:301:22: error: assignment to ‘uint8_t *’ {aka ‘unsigned char *’} from ‘int’ makes pointer from integer without a cast -Wint-conversion]
  301 |                 rsne = alloca(256);
      |                      ^
src/fils.c: In function ‘fils_free’:
src/fils.c:350:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  350 |         explicit_bzero(fils->ick, sizeof(fils->ick));
      |         ^~~~~~~~~~~~~~