eap-md5: Fix build issue with missing _GNU_SOURCE
  CC       src/eap-md5.o
src/eap-md5.c: In function ‘eap_md5_free’:
src/eap-md5.c:46:17: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
   46 |                 explicit_bzero(md5->secret, strlen(md5->secret));
      |                 ^~~~~~~~~~~~~~