knownnetworks: Fix build issue with missing _GNU_SOURCE
  CC       src/knownnetworks.o
src/knownnetworks.c: In function ‘known_networks_init’:
src/knownnetworks.c:1100:39: error: ‘DT_UNKNOWN’ undeclared (first use in this function)
 1100 |                 if (dirent->d_type == DT_UNKNOWN) {
      |                                       ^~~~~~~~~~
src/knownnetworks.c:1100:39: note: each undeclared identifier is reported only once for each function it appears in
src/knownnetworks.c:1103:46: error: ‘DT_REG’ undeclared (first use in this function)
 1103 |                 } else if (dirent->d_type != DT_REG &&
      |                                              ^~~~~~
src/knownnetworks.c:1104:67: error: ‘DT_LNK’ undeclared (first use in this function)
 1104 |                                                 dirent->d_type != DT_LNK) {
      |                                                                   ^~~~~~