mschaputil: Fix build issue with missing _GNU_SOURCE
  CC       src/mschaputil.o
src/mschaputil.c: In function ‘mschap_des_encrypt’:
src/mschaputil.c:55:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
   55 |         explicit_bzero(pkey, 8);
      |         ^~~~~~~~~~~~~~