netdev: Fix build issue with missing _GNU_SOURCE
  CC       src/netdev.o
src/netdev.c: In function ‘pae_open’:
src/netdev.c:6606:40: error: ‘SO_ATTACH_FILTER’ undeclared (first use in this function)
 6606 |         if (setsockopt(fd, SOL_SOCKET, SO_ATTACH_FILTER,
      |                                        ^~~~~~~~~~~~~~~~
src/netdev.c:6606:40: note: each undeclared identifier is reported only once for each function it appears in