eap-mschapv2: Fix build issue with missing _GNU_SOURCE
  CC       src/eap-mschapv2.o
src/eap-mschapv2.c: In function ‘eap_mschapv2_state_free’:
src/eap-mschapv2.c:202:9: error: implicit declaration of function ‘explicit_bzero’ [-Wimplicit-function-declaration]
  202 |         explicit_bzero(state->password_hash, sizeof(state->password_hash));
      |         ^~~~~~~~~~~~~~